name 'pankaj_chef_docker'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures pankaj_chef_docker'
long_description 'Installs/Configures pankaj_chef_docker'
version '0.1.0'
